### ISSUE TITLE
Connection Refused！

### ISSUE THREAD

**Issue by goodmight** [zzzzls/WXFileHelper#2]
requests.exceptions.ProxyError: HTTPSConnectionPool(host='login.wx.qq.com', port=443): Max retries exceeded with url: /jslogin?appid=wx_webfilehelper&redirect_uri=https%253A%252F%252Fszfilehelper.weixin.qq.com%252Fcgi-bin%252Fmmwebwx-bin%252Fwebwxnewloginpage&fun=new&lang=zh_CN&_=1650782074521 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde0edce520>: Failed to establish a new connection: [Errno 111] Connection refused')))

完整报错如下

Traceback (most recent call last):
  File "/home/username/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/home/username/anaconda3/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/home/username/anaconda3/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/username/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "/home/username/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "/home/username/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/home/username/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fde0edce520>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/username/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/username/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/username/anaconda3/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='login.wx.qq.com', port=443): Max retries exceeded with url: /jslogin?appid=wx_webfilehelper&redirect_uri=https%253A%252F%252Fszfilehelper.weixin.qq.com%252Fcgi-bin%252Fmmwebwx-bin%252Fwebwxnewloginpage&fun=new&lang=zh_CN&_=1650782074521 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde0edce520>: Failed to establish a new connection: [Errno 111] Connection refused')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/username/proj/wxFileHelper/realWXFileHelper.py", line 493, in <module>
    filehelper = WXFilehelper()
  File "/media/username/proj/wxFileHelper/realWXFileHelper.py", line 360, in __init__
    if self.wait_login():
  File "/media/username/proj/wxFileHelper/realWXFileHelper.py", line 367, in wait_login
    uuid = self.__generate_QRLogin_uuid()
  File "/media/username/proj/wxFileHelper/realWXFileHelper.py", line 394, in __generate_QRLogin_uuid
    resp = self.wx_req.fetch(url, params=params)
  File "/media/username/proj/wxFileHelper/realWXFileHelper.py", line 342, in fetch
    resp = self.session.request(
  File "/home/username/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/username/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/username/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='login.wx.qq.com', port=443): Max retries exceeded with url: /jslogin?appid=wx_webfilehelper&redirect_uri=https%253A%252F%252Fszfilehelper.weixin.qq.com%252Fcgi-bin%252Fmmwebwx-bin%252Fwebwxnewloginpage&fun=new&lang=zh_CN&_=1650782074521 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde0edce520>: Failed to establish a new connection: [Errno 111] Connection refused')))

Process finished with exit code 1

**Comment by goodmight** [comment]
是因为header的伪装（还是没有伪装啊）被识别出来了吗？

**Comment by zzzzls** [comment]
> 是因为header的伪装（还是没有伪装啊）被识别出来了吗？

建议检查一下你电脑的 VPN，「http_proxy」环境变量等

**Comment by goodmight** [comment]
> 建议检查一下你电脑的 VPN，「http_proxy」环境变量等

em 有点疑惑。
1. 如果是VPN或者环境变量的问题的话，难道不应该浏览器也无法访问吗？可我浏览器可以访问它俩啊
  WX_LOGIN_HOST = "https://login.wx.qq.com"
  WX_FILEHELPER_HOST = "https://szfilehelper.weixin.qq.com"
2. http_proxy环境变量是指系统的环境变量吗？类似翻墙代理？

**Comment by zzzzls** [comment]
> 

是的，或者你可以写一个 requests 脚本，请求上述两个 url，测试是否成功

**Comment by goodmight** [comment]
343 行的 proxies={'https': 'http://127.0.0.1:8888'} 注释掉就好了
